.TH "repos/CS1D ExCr1 Extendable Array Directory Reference" 3 "Wed Feb 12 2020" "Version 1" "CS1D - Extra Credit 1  - Extendable Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repos/CS1D ExCr1 Extendable Array Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCS1D ExCr1 Extendable Array\fP"
.br
.in -1c
