.TH "repos/CS1D ExCr1 Extendable Array/CS1D ExCr1 Extendable Array/Except.h" 3 "Wed Feb 12 2020" "Version 1" "CS1D - Extra Credit 1  - Extendable Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repos/CS1D ExCr1 Extendable Array/CS1D ExCr1 Extendable Array/Except.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExcept\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBERROR_TYPE\fP { \fBDEFUALT\fP, \fBFULL\fP, \fBEMPTY\fP, \fBOUT_OF_RANGE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBERROR_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDEFUALT \fP\fP
.TP
\fB\fIFULL \fP\fP
.TP
\fB\fIEMPTY \fP\fP
.TP
\fB\fIOUT_OF_RANGE \fP\fP
.PP
Definition at line 17 of file Except\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Extra Credit 1 - Extendable Array from the source code\&.
