.TH "repos/CS1D ExCr1 Extendable Array/CS1D ExCr1 Extendable Array/main.h" 3 "Wed Feb 12 2020" "Version 1" "CS1D - Extra Credit 1  - Extendable Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repos/CS1D ExCr1 Extendable Array/CS1D ExCr1 Extendable Array/main.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'PrintHeader\&.h'\fP
.br
\fC#include 'ExtendableArray\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Extra Credit 1 - Extendable Array from the source code\&.
