.TH "repos/CS1D ExCr1 Extendable Array/CS1D ExCr1 Extendable Array/PrintHeader.h" 3 "Wed Feb 12 2020" "Version 1" "CS1D - Extra Credit 1  - Extendable Array" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repos/CS1D ExCr1 Extendable Array/CS1D ExCr1 Extendable Array/PrintHeader.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPrintHeader\fP (std::ostream &output, std::string inputText)"
.br
.RI "Print header\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBPROGRAMMER\fP = 'Nick Reardon'"
.br
.ti -1c
.RI "const std::string \fBSECTION\fP = 'MW \- 2:30p'"
.br
.ti -1c
.RI "const std::string \fBCLASS\fP = 'CS1D'"
.br
.ti -1c
.RI "const int \fBPROGRAM_NUM\fP = 1"
.br
.ti -1c
.RI "const std::string \fBPROGRAM_NAME\fP = 'Extendable Array'"
.br
.ti -1c
.RI "const std::string \fBPROGRAM_TYPE\fP = 'Extra Credit'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void PrintHeader (std::ostream & output, std::string inputText)"

.PP
Print header\&. 
.PP
\fBParameters\fP
.RS 4
\fIoutput\fP ostream output 
.br
\fIinputText\fP file name of the prompt text file 
.RE
.PP

.PP
Definition at line 70 of file PrintHeader\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const std::string CLASS = 'CS1D'"

.PP
Definition at line 58 of file PrintHeader\&.h\&.
.SS "const std::string PROGRAM_NAME = 'Extendable Array'"

.PP
Definition at line 60 of file PrintHeader\&.h\&.
.SS "const int PROGRAM_NUM = 1"

.PP
Definition at line 59 of file PrintHeader\&.h\&.
.SS "const std::string PROGRAM_TYPE = 'Extra Credit'"

.PP
Definition at line 61 of file PrintHeader\&.h\&.
.SS "const std::string PROGRAMMER = 'Nick Reardon'"

.PP
Definition at line 56 of file PrintHeader\&.h\&.
.SS "const std::string SECTION = 'MW \- 2:30p'"

.PP
Definition at line 57 of file PrintHeader\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Extra Credit 1 - Extendable Array from the source code\&.
